name: bcchildcarevacancybot

on:
  push:
    branches: ['test'] # push to this branch to test toots
  schedule:
    - cron: '41 15 * * *'  # trigger at 5am and 4pm every day

jobs:
  tweet:
    runs-on: ubuntu-latest
    env:
      RTOOT_DEFAULT_TOKEN: ${{ secrets.RTOOT_DEFAULT_TOKEN}}
      TWITTER_CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
      TWITTER_CONSUMER_API_SECRET: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            rtoot
            purrr
            readr
            lubridate
            glue
            tidyr
            dplyr
            forcats
      - name: Create message and tweet toot
        run: Rscript tweet_toot.R
