name: bcchildcarevacancybot

on:
  push:
    branches: ['main']
  schedule:
    - cron: '33 5,16 * * *'  # trigger at 5am and 4pm every day

jobs:
  tweet:
    runs-on: ubuntu-latest
    env:
      RTOOT_DEFAULT_TOKEN: ${{ secrets.RTOOT_DEFAULT_TOKEN}}
      TWITTER_CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
      TWITTER_CONSUMER_API_SECRET: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Install system dependencies
        run: sudo apt install -y libcurl4-openssl-dev
      - uses: r-lib/actions/setup-r@v2
      - name: Install R packages
        run: Rscript -e 'install.packages(c("rtoot", "rtweet", "purrr", "readr", "lubridate", "glue", "tidyr"), dependencies = TRUE)'
      - name: Create and tweet
        run: Rscript tweet_toot.R
